use CleanAPIDb
go

CREATE TABLE APICredentials (
    Id INT IDENTITY PRIMARY KEY,
    Username NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(256) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE APITokens (
    Id INT IDENTITY PRIMARY KEY,
    CredentialId INT NOT NULL,
    Token UNIQUEIDENTIFIER NOT NULL,
    Expiry DATETIME2 NOT NULL,
    CONSTRAINT FK_APITokens_Creds FOREIGN KEY (CredentialId)
        REFERENCES APICredentials(Id)
);

CREATE TABLE Products (
    Id INT IDENTITY PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
ALTER TABLE APICredentials
ADD
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    LastUsedAt DATETIME2 NULL;
ALTER TABLE APITokens
ADD ClientIp NVARCHAR(45) NOT NULL;

INSERT INTO APICredentials (Username, PasswordHash)
VALUES ('admin', HASHBYTES('SHA2_256', 'admin123'));
